Readme part2
actlab-fhy/FhY pull request #10
Opened 2024-05-31 20:11 UTC by Spill-Tea

Finalize edits to Readme Doc

2024-06-03 22:42 UTC, christopherpriebe requested changes
change one thing

2024-06-03 22:42 UTC, christopherpriebe commented on README.md
> +users to review the design blog for more information regarding *FhY* and as a starting
end of sentence does not make sense; seems like it was split from prior sentence

2024-06-04 02:38 UTC, Spill-Tea commented on README.md
> +users to review the design blog for more information regarding *FhY* and as a starting
I have updated paragraph to be less of a run-on sentence at the end.

2024-06-04 15:22 UTC, christopherpriebe approved these changes
LGTM

2024-06-04 15:54 UTC, merged