Cli
actlab-fhy/FhY pull request #11
Opened 2024-06-03 23:35 UTC by Spill-Tea

Convert of CLI to use a Typer Application, and begin to carve out future CLI options / commands / arguments.

2024-06-04 02:55 UTC, Spill-Tea commented
For reference, this is the default help menu display:

```bash
fhy --help
```
<img width="549" alt="Screenshot 2024-06-03 at 7 45 12 PM" src="https://github.com/actlab-fhy/FhY/assets/61038372/7751a7f3-6a23-418c-9e4f-9c2ca6310c0a">

And for the subcommand
```bash
fhy serialize --help
```
<img width="533" alt="Screenshot 2024-06-03 at 7 45 36 PM" src="https://github.com/actlab-fhy/FhY/assets/61038372/cad12be3-6f42-4634-a9ae-263025b6bfd9">


Using an environment variable, we can modify the help menu display to use rich text formatting as shown:

<img width="865" alt="Screenshot 2024-06-03 at 7 52 36 PM" src="https://github.com/actlab-fhy/FhY/assets/61038372/ee13036d-9008-47a7-bd5e-3e9658afcfa9">

<img width="867" alt="Screenshot 2024-06-03 at 7 52 55 PM" src="https://github.com/actlab-fhy/FhY/assets/61038372/a7906c3b-bca2-4dc8-8552-612b96f618a8">

2024-06-10 15:34 UTC, christopherpriebe requested changes

2024-06-10 15:34 UTC, christopherpriebe commented on src/fhy/cli.py
> +class Namespace:
What is a namespace here? Our language has namespaces like Python does. This is confusing to me.

2024-06-10 15:34 UTC, christopherpriebe commented on src/fhy/cli.py
> +    module: Annotated[
I don't like the --module vs. --library command like arguments. I think that the keyword arguments specify compilation options. A user should be able to compile a FhY file without having to use any keyword arguments. The CLI should take in ONLY the root file containing the main procedure and compile from there.

2024-06-10 15:34 UTC, christopherpriebe commented on src/fhy/lang/converter/from_parse_tree.py
> +    return Span(0, 0, 0, 0, source)
Span should be an optional field in the AST node and then this should return None here.

2024-06-11 17:24 UTC, christopherpriebe requested changes
Some small things but overall it looks good.

Oh, also, if you can make the "usage" part of the help menu make more sense that would be awesome because right now it just says "Usage: fhy [OPTIONS] COMMAND [ARGS]..." instead of something more useful like "Usage: fhy [OPTIONS] MAIN_FILE.fhy" or something idk

2024-06-11 17:24 UTC, christopherpriebe commented on src/fhy/cli.py
> +def compiles(
Is there a better name that uses an active phrase rather than a passive one?

2024-06-11 17:24 UTC, christopherpriebe commented on requirements.txt
> +typer
change this to typer-slim. I think we should make the full typer install an optional dependency rather than the default

2024-06-11 21:12 UTC, christopherpriebe commented
lgtm!

2024-06-11 21:13 UTC, christopherpriebe approved these changes
lgtm!

2024-06-11 21:23 UTC, merged