Basic type system implementation
actlab-fhy/FhY pull request #17
Opened 2024-06-18 19:17 UTC by christopherpriebe

Added the type promotion lattice for the primitive data types and the promotion functions for both primitive data types and type qualifiers. Also included basic unit tests.

2024-06-18 22:17 UTC, Spill-Tea requested changes

2024-06-18 22:17 UTC, Spill-Tea commented on src/fhy/ir/type.py
> +        stride (Optional[Expression]): Step size.
Update Stride argument type to:
(Expression, optional)

2024-06-18 22:17 UTC, Spill-Tea commented on src/fhy/utils/lattice.py
> +    def add_element(self, element: T):
explicitly include return type -> None

2024-06-18 22:17 UTC, Spill-Tea commented on src/fhy/utils/lattice.py
> +    def add_order(self, lower: T, upper: T):
Same. Explicitly include return type -> None

2024-06-18 22:17 UTC, Spill-Tea commented on src/fhy/utils/lattice.py
> +        Returns (bool): True if x and y have a greatest lower bound,
For all following methods, update docstrings using google convention, where return is it's own section:
```
Returns:
    (type) ...
```

2024-06-18 22:17 UTC, Spill-Tea commented on src/fhy/ir/type.py
> +def _define_uint_data_type_lattice() -> Lattice[PrimitiveDataType]:
Just a Comment - let's discuss type promotions, and write up a blog on what FhY currently supports explicitly. For example, We may potentially want to support type promotions from unsigned to signed integer, and consider how we want to handle uint64, or provide a cli flag to support unsafe (i.e. at loss or expense of precision) type promotions from int to floats.

2024-06-19 00:56 UTC, Spill-Tea commented
One Final Note: Make sure to link fixes to the jira ticket.

2024-07-10 16:25 UTC, christopherpriebe commented on src/fhy/ir/type.py
> +def _define_uint_data_type_lattice() -> Lattice[PrimitiveDataType]:
For now, we can merge. We will put this up for discussion in the future.

2024-07-10 17:33 UTC, Spill-Tea requested changes
Just update the docstrings in both the lattice and partially ordered set utils modules. Otherwise looks good.

2024-07-10 17:33 UTC, Spill-Tea commented on src/fhy/utils/lattice.py
> +        """Returns True if the lattice is a valid lattice, False otherwise."""
Use active voice here in docstring:

"""Return True if the lattice is a valid lattice, False otherwise."""
"""Evaluate if lattice is valid."""

2024-07-10 17:33 UTC, Spill-Tea commented on src/fhy/utils/lattice.py
> +        Returns (bool):
Modify Return sections in docstrings of lattice and partially ordered set class methods such that the type 
(or description) is not defined inline:
```python
"""
Return:
    (return type): ...description...

"""
```

2024-07-10 18:12 UTC, Spill-Tea approved these changes
lgtm!

2024-07-10 18:17 UTC, merged