Template types
actlab-fhy/FhY pull request #19
Opened 2024-06-25 22:45 UTC by Spill-Tea

Further support Template types - We previously made template types as identifier expressions without much further massaging.

1. ir.DataType is now an abstraction, with two child classes: Primitive and Template
2. Update FhY Grammar to support Template types in both function header and function expression (calls).
3. Update the parse tree converter construct and update a chain map for new available (template) types in different scopes. I also initialized base primitive types as identifiers, but this is may not be relevant.
4. Update JSON and pformat -> need to double check further. in Current tests, our template types are empty.

2024-06-27 17:38 UTC, christopherpriebe requested changes
Check my comments. Sending this comment from 30K feet!

2024-06-27 17:38 UTC, christopherpriebe commented on CONTRIBUTING.md
> +   environment may differ here on diffent OS and shells)
*different

2024-06-27 17:38 UTC, christopherpriebe commented on CONTRIBUTING.md
> +   possible implementation details, or nuances.
no comma

2024-06-27 17:38 UTC, christopherpriebe commented on CONTRIBUTING.md
> +[goole's style guide](https://google.github.io/styleguide/pyguide.html).
Google?

2024-06-27 17:38 UTC, christopherpriebe commented on grammar/FhY.g4
> +    : function_type=FUNCTION_KEYWORD name=IDENTIFIER (LESS_THAN function_template_types=expression_list GREATER_THAN)? (OPEN_BRACKET function_indices=function_args CLOSE_BRACKET)? OPEN_PARENTHESES fu
Can you explain the change from an identifier list here to an expression list? My vision here was that a generic type is just a symbol that will be substituted with some other valid data type at compile time. So, from my point of view, the only possibilities are to have identifiers for the generics themselves. Later in the grammar, there is the rule a function expression where a function is called. In this rule, the current grammar rule for the template types is an expression list. This should be changed to a list of "dtypes" from my point of view. Then, you can have this as valid code.
```
proc foo<T, R>(input T[M] a, input R[M] b, output T[M] c) {
    temp index[1:M] i;
    c[i] = a[i] + b[i];
}

proc main(input fxp<16>[5] a, input int8[5] b, output fxp<16>[5] c) {
    foo<fxp<16>, int8>(a, b, c);
}
```

2024-06-27 17:38 UTC, christopherpriebe commented on src/fhy/ir/type.py
> +        data_type (PrimitiveDataType | Identifier):
I don't think this abstract class should have this attribute. It could have some abstractmethods to tell properties about the datatype but I don't think it should store anything. That doesn't make sense in my opinion as the child classes should define the attribute for storing either the primitive datatype or the identifier for the template. You could even make the PrimitiveDataType class a subclass of both strenum and the DataType base class without going through the additional level of indirection.

2024-06-27 17:38 UTC, christopherpriebe commented on src/fhy/lang/ast/pprint.py
> +        return str(node.template_type)  # NOTE: Double check this.
this looks right to me no need for a note.

2024-06-27 20:58 UTC, Spill-Tea commented on grammar/FhY.g4
> +    : function_type=FUNCTION_KEYWORD name=IDENTIFIER (LESS_THAN function_template_types=expression_list GREATER_THAN)? (OPEN_BRACKET function_indices=function_args CLOSE_BRACKET)? OPEN_PARENTHESES fu
So my only rationale behind modifying to an expression list was for more consistency in how we treated function calls and function headers. Alright, so we...

1. Revert the function header back to a list of Identifiers.
2. Function expression (calls) require a list of dtypes (not an expression list).

This means that our DataType child classes require an additional field defining bit size (that defaults to None)? Do we anticipate this "nested" template dtype to be a list here, or at most one element? Do we only expect int Literals here? or other template types (identifiers)? For example, of increased complexity:

`foo<fxp<16, 8>, T<K, V>(a, b, c);`

I don't anticipate either of these cases, but may be worth discussing embedded template types (e.g. if we foresee FhY language expanding to include classes or struct).

2024-07-01 14:48 UTC, christopherpriebe commented on grammar/FhY.g4
> +    : function_type=FUNCTION_KEYWORD name=IDENTIFIER (LESS_THAN function_template_types=expression_list GREATER_THAN)? (OPEN_BRACKET function_indices=function_args CLOSE_BRACKET)? OPEN_PARENTHESES fu
First; don't bother adding the bits required to data type yet. Leave this as a feature in the grammar but not in the language. If someone used this syntactical feature, we will throw a not implemented error. As for the nested example you provided, it is not valid. Each generic T represents a data type. fxp<16, 8> is a data type in itself. So this T<K, V> doesn't make sense. T is the data type itself (it includes the angle brackets).

2024-07-01 19:18 UTC, Spill-Tea commented on src/fhy/ir/type.py
> +        data_type (PrimitiveDataType | Identifier):
Agreed. This is now fixed.

2024-07-01 21:06 UTC, christopherpriebe requested changes
I have left comments. I feel we are swinging back and forth on this.

2024-07-01 21:06 UTC, christopherpriebe commented on grammar/FhY.g4
> +    : function_type=FUNCTION_KEYWORD name=IDENTIFIER ( function_template_types=dtype_list )? (OPEN_BRACKET function_indices=function_args CLOSE_BRACKET)? OPEN_PARENTHESES function_args CLOSE_PARENTHE
This should be an identifier_list??? The template types in the function header are not dtypes syntactically. They do not have the option to have a angle bracket parameters.

2024-07-01 21:06 UTC, christopherpriebe commented on grammar/FhY.g4
> +    : LESS_THAN (dtype (COMMA dtype)* COMMA?)? GREATER_THAN
Don't put the less_than and greater_than in this rule. Move it back to the original location in the function header and the function call like before.

2024-07-01 21:06 UTC, christopherpriebe commented on src/fhy/ir/type.py
> +    def __init__(self, data_type: PrimitiveDataType) -> None:
Now that I think about it, I think this nesting is completely unnecessary. While the angle bracket parameters are syntactically available to the user, make it something in the conversion from the CST to the AST that throws a NotImplementedError. There should be a PrimitiveDataType class and a TemplateDataType class. Primitive and Template are not descriptive enough. We can modify the PrimitiveDataType class from an StrEnum to a more complicated implementation when we intend to support the angle bracket parameters for the data types. For now, this feature is syntactically available only.

2024-07-08 03:00 UTC, christopherpriebe requested changes
The code looks good; need to go and address docstring issues; looks like just a mistake with find and replace across repo; should be quick fix and then merge.

2024-07-08 03:00 UTC, christopherpriebe commented on src/fhy/ir/type.py
> +        data_type (Identifier): template type identifier
Should capitalize the first word in these arg portions of the docstring.

2024-07-08 03:00 UTC, christopherpriebe commented on src/fhy/lang/ast/node/statement.py
> +        templates (List[ir.Identifier], optional): TemplateDataType types.
All the places with the "Template types." description previous were correct. Looks like just a mistake with a find and replace command across the repo. Please change back.

2024-07-08 03:00 UTC, christopherpriebe commented on src/fhy/lang/ast/visitor.py
> +            node (ir.TemplateDataType): TemplateDataType data type node to transform.
Should just be "Template data type node to transform"

2024-07-08 22:28 UTC, christopherpriebe approved these changes
lgtm!

2024-07-08 22:49 UTC, merged