Blog post recap on Compiler Meeting.
actlab-fhy/FhY pull request #5
Opened 2024-04-25 23:46 UTC by Spill-Tea

Blog Post Recapping our Compiler Meeting Discussions from Monday 22 April 2024.

2024-05-23 23:55 UTC, christopherpriebe requested changes
Please see my feedback 👯‍♂️

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +    3. We initially had troubles parsing Floating Point Numbers, discovered by our unit
First, I wouldn't personally capitalize floating point numbers. Second, I think that we could speculate that our parser rule for getting integer literals was overriding our parser rule for floating point literals or that our lexing rule for integer literals was being used and causing the components for the floating point literals in the parser rule to be consumed by the integer lexer rule. Is this what you saw in your experience?

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       We are currently calling this conversion, "pretty printing," because we can
I would say here that the pretty printing is not for converting back into the original language. Even though it does in fact look like the original language and would be parsed correctly with the default settings, if you added the ID print, then it is no longer valid FhY. It is mostly for a more readable format. Maybe we can say that it will be valid FhY if no additional options are set, but further configuration causes invalid FhY code to be returned.

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +    5. We have setup a Github workflow, for CI/CD, which automatically builds our Antlr
"GitHub" and "ANTLR"; also, ANTLR generated files should be ANTLR-generated files

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       checking analysis. Previously, We had setup a tox configuration file used for
"we" needs to be lower case.

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       github workflow, for more consistent testing paradigm both locally and remotely.
GitHub, no need for a comma after workflow; also, "for a more" rather than "for more"

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       Further note, that we are currently only supporting python>=3.11, due to use of
"Further note, we are currently only supporting Python versions >=3.11 due to the use of the StrEnum class, but we hope to change that soon."

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +    1. Serialization: Using a visitor pattern, write a class to convert ASTNodes to json
JSON

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +    2. ASTNode Passes: Write simple passes to our ASTNodes to perform Label and Type
ASTNode Passes: Write simple passes over our AST to perform label and type checking.

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +    4. Write a script (cli) for FhY, to perform compilation from the command line, by
no commas here :D

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +          purposes, and build up our current tool chain.
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       code, is not scalable. Extract out example FhY Code into separate input and
no comma after code

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +    *  Note that the term `visitor pattern` is a little ambiguous, on whether they
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       are constructing entirely new nodes, but the ASTNode Passes do not (i.e. are
We have the Transformer class so this is not true anymore :/

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       python, then rust. Future expansion of coding support will be strategized after
Capitalize Python and Rust

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       class to deconstruct ASTNodes back into FhY Code, and are focusing on json format
See my note about pretty printing FhY from earlier; also, JSON!

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +- **Release Date**: Thursday 25th April 2024
See my note from earlier about dates

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +#IntegrationTests #UnitTests #CodingCoverage #CornerCases #TestingStrategy
plz no hashtags 😭

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +from a base ASTNode, and stages our core nodes to express fundamental grammar constructs
What do you mean by "stages our core nodes"?

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +using our FhYListener class generated by Antlr, we had conflicting requirements for our
No comma after CST and also ANTLR

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +In our initial approach to constructing AST Nodes from a Concrete Syntax Tree (CST),
Overall in this paragraph, don't capitalize "Nodes" if separated from AST.

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +accepted an ASTNode class, to dynamically define mutable attribute fields. Coupled with
no comma here

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +       implemented a visitor pattern, which became much more straightforward and
I think that the blurb put in the following blog post about why we switched to a visitor pattern is much better than this blurb. Maybe you can revise it? I know there were issues with ambiguity but this reason is much more concrete and easier to put a finger on and prove.

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +to validate our current production status meets our requirements, and make it possible
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +it does increase our confidence in anticipated variety of input source fhy code is
FhY; also, this is a run on sentence; plz revise

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +testing to confirm we raise errors (specifically syntax errors) when incorrect fhy code
FhY

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +forgetting the argument variable name, can slip though parsing by antlr:
ANTLR; no comma after name

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +This means we need to throw a syntax error, when we discover this during construction of
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +the ast so that we fail fast, and provide the user with enough information to resolve
AST; no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +After our discussion earlier this week, we have created a unified cli entry point to
I think CLI should be capitalized as it is an acronym

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +our fhy package. After installation, it can be called through the command line like so:
FhY

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +.. code-block:: bash
Not really a documentation issue, but I would prefer the CLI to have "module"/"library" as a "mode" of the CLI. For example, typing like "fhy module <filepath>"

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +Sample directory containing expected input and output (text) files, which can be batch
lower case sample even though the directory is upper case because we will change that sometime! Also, no comma before which

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +adding a new example fhy code, it will automatically be tested. And if you forgot to add
FhY

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +We also can serialize our AST Nodes to json format, using the subparser `serialize`:
JSON; subparser? subpackage I think haha

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +This will stream the json format to stdout, which makes it possible to pipe to compare
JSON

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +package) using subprocess against input fhy source code files, and comparing against
FhY; no comma before and

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +#CustomExceptions #ErrorPolicy #FhY #Debugging #ErrorMessage
plz

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +therefore important to facilitate easier debugging. Ultimately what we want, is
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +diagnose, and handle what exceptions may be raised when using FhY Software. Furthermore,
software

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +1. Define all Custom exceptions in a single module (e.g. fhy/utils/error.py).
custom

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +    b. One minor downside of this approach, is that we don't know exactly where each
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +    a. Custom errors are defined closer to where they are used throughout the fhy
FhY

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +       allows us to register builtin python Exceptions (especially if not all are used).
Python; exceptions (I guess its ok to be capitalized if you are referring to the class)

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +provide a succinct description of the intended use, followed by an example message
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +documentation of each custom exception will provide an example message, to define
no comma

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +its usage. Multiple Examples may be provided. We also provide general exception message
examples

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +      raise TypeError(f"Expected `value` argument type `str`. Received: {type(value)}")
should decide on the quotes style for the inner quotes

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +2. When describing Errors derived from input source code, the error message should
errors

2024-05-23 23:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-02.rst
> +- **Release Date**: Thursday 2nd May 2024
Date format comment from earlier

2024-05-24 19:15 UTC, Spill-Tea commented on docs/source/design_blog/post_2024-04-22.rst
> +    3. We initially had troubles parsing Floating Point Numbers, discovered by our unit
Correct. This was an issue with the token precedence that ANTLR imposes.

2024-05-24 21:57 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-10.rst
> +- **Last Updated**: Thursday 11th April 2024
Yes, this is good!

2024-05-24 21:58 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +#ListenersVsVisitors #AntlrGrammarWoes #ChainMaps #UniqueIDs #Serialization #CLI
Let's leave these out for the time being.

2024-05-24 21:59 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +We also can serialize our AST Nodes to json format, using the subparser `serialize`:
Ah, I understand this is in reference to a command-line argument. Thanks!

2024-05-24 22:29 UTC, christopherpriebe approved these changes
After changes, LGTM

2024-05-24 23:23 UTC, merged