Post ci coverage
actlab-fhy/FhY pull request #8
Opened 2024-05-25 00:44 UTC by Spill-Tea

Draft a New Blog discussing the intricacies of correctly capturing coding coverage in a tox virtual environment, python project packaging structures, and our implementation of our final scalable workflow.

2024-05-28 23:42 UTC, christopherpriebe requested changes
Great job! Good detail and research done. Just fix grammar and explain a sentence to me.

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-04.rst
> +-  **Last Updated**: Friday May 24th, 2024
So I meant for these "Last Updated" dates to be for changes to the specific blog post, not for all of the blog posts. Sorry that I did not communicate this. I wanted it there in case there were small edits that needed to be made so that previous blog posts were up to date.

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-05.rst
> +-  **Last Updated**: Friday May 24th, 2024
same as above

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-10.rst
> +-  **Last Updated**: Friday May 24th 2024
Same as above

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-22.rst
> +-  **Last Updated**: Friday May 24nd, 2024
same as above

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-04-25.rst
> +-  **Last Updated**: Thursday May 23rd, 2024
same as above

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +tests that use subprocess against our fhy entry point. Initially, the only way i was
FhY? idk. Also, capitalize "i"

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +able to solve this was to use a development environment, configured in the tox.ini file
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +separated unit testing only (in normal installed environment), and a separate coverage
what does this sentence mean im confused sorry

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +This initially worked fine, because we are only testing a single python version.
no comma; also, Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +However, we would like to scale to support both multiple python versions and host OS's
Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +Furthermore, because we plan to matrix both OS and python versions, we do not need to
Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +report both in github actions and locally. We no longer would need to endlessly scroll
GitHub Actions

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +Every package I had previously developed or managed didn't have a script, or entry point
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +are testing against the local copy (within the project root). But our Integration tests
integration

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +It's easy to forget when using tox, that the local copy of your source code is visible
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +to it, because everything is happening "behind the scenes". What we really want while
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +using tox, is to perform all of our testing against our installed package (within the
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +This was the general structure which followed standard python packaging convention
Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +site-packages because both are on path. The easiest solution is to change that, by
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +correctly using setuptools, and the coverage tool. In our pyproject.toml:
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +coding coverage of your project, using tox virtual environments, even if you need to
remove first comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +also capture subprocess, or multiple parallel processes.
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +#. Guidance on best practices to setup your python project is currently `evolving
Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +   setting up your (next) python project to make certain it is not importable during
Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +   testing. This src layout project structure is most compatible with tox, to ensure all
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +#. Use `coverage.py` directly when monitoring code coverage, forgoing the pytest plugin,
remove second comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +#. Update your pyproject.toml if using setuptools to correctly find your python package,
Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +   relevant sections in completion, below:
no comma

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +   documentation build all performed on a single os and python version. In a parallel
OS, Python

2024-05-28 23:42 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +   environment, we can matrix python versions and Host OS platforms, to perform pytest
Python, host OS, remove second comma

2024-05-29 03:46 UTC, Spill-Tea commented on docs/source/design_blog/post_2024-05-23.rst
> +separated unit testing only (in normal installed environment), and a separate coverage
Apparently I had a mild stroke, or tried to write two separate sentences at the same time.
I am trying to communicate that I created two separate environments. One in development mode (performing pytest + pytest-cov), and another using standard installation (performing pytest only).

2024-05-29 13:55 UTC, christopherpriebe requested changes
one more thing

2024-05-29 13:55 UTC, christopherpriebe commented on docs/source/design_blog/post_2024-05-23.rst
> +If the the answer isn't obvious yet, we are calling PyTest from the project root
Funny enough, like tox, when the authors use pytest in their documentation, they do not capitalize the P unless it is at the beginning of a sentence. (https://en.wikipedia.org/wiki/Pytest)

2024-05-29 15:50 UTC, Spill-Tea commented on docs/source/design_blog/post_2024-05-23.rst
> +If the the answer isn't obvious yet, we are calling PyTest from the project root
Done. Fixed all instances of capitalization of PyTest to pytest

2024-05-29 16:03 UTC, christopherpriebe approved these changes
LGTM

2024-05-29 16:45 UTC, merged